@startuml
actor Engineer
database DB

participant Engineer order 10
participant web_app order 0

box "SnortRuleGenerator"
participant Application
participant DB
end box



Engineer -> Application: Запуск
activate Application
Application -> Application: Старт захвата\nтрафика
activate Application #ccc
Engineer -> web_app: Атака\nприложения
activate web_app
Engineer -> Application: Стоп
deactivate web_app
Application -> Application: Остановка захвата
deactivate Application

Application -> DB:  Сохранение \nзахваченных пакетов
Application <-- DB: Загрузка известных\nправил
note left: 1 ?
Application -> Application: Анализ содержимого\nтрафика
note left: 2 ?
return Файл с правилами



@enduml