openapi: 3.0.1
info:
  title: Snort Rule Generator Api
  version: 0.0.1
servers:
  - url: /
tags:
  - name: Events
    description: Attack events
  - name: Definitions
    description: Definitions
  - name: Analyzer
    description: Run or Stop traffic analyzer
paths:
  /events:
    get:
      tags:
        - Events
      summary: Get events
      operationId: get_events
      parameters:
        - name: offset
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: Events list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                x-content-type: application/json
      x-openapi-router-controller: api.controllers.events_controller
  /analyzer/start:
    post:
      tags:
        - Analyzer
      summary: Start traffic analyzer
      operationId: start_traffic_analyzer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-body-name: start_request
      responses:
        204:
          description: Started successfully
      x-openapi-router-controller: api.controllers.analyzer_controller
  /analyzer/stop:
    post:
      tags:
        - Analyzer
      summary: Start traffic analyzer
      operationId: stop_traffic_analyzer
      responses:
        204:
          description: Stopped successfully
      x-openapi-router-controller: api.controllers.analyzer_controller

  /rules:
    get:
      tags:
        - Rules
      summary: Get SNORT rules
      operationId: get_rules
      responses:
        200:
          description: List of rules
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      x-openapi-router-controller: api.controllers.rule_controller

    delete:
      tags:
        - Rules
      summary: Remove ALL SNORT rules
      operationId: remove_rules
      responses:
        204:
          description: Rules deleted
      x-openapi-router-controller: api.controllers.rule_controller

  /signs:
    post:
      tags:
        - Signs
      summary: Create signs
      operationId: create_sign
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-body-name: data
      responses:
        204:
          description: Created successfully
      x-openapi-router-controller: api.controllers.signs_controller

    get:
      tags:
        - Signs
      summary: Get signs
      operationId: get_signs
      parameters:
        - name: offset
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: List of definitions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      x-openapi-router-controller: api.controllers.signs_controller

  /signs/{sign_id}:
    delete:
      tags:
        - Signs
      summary: Remove signs
      operationId: remove_sign
      parameters:
        - name: sign_id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: sign deleted
      x-openapi-router-controller: api.controllers.signs_controller

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
      example:
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
    Reader:
      type: string
      enum:
        - pcap
        - interface
    StartRequest:
      type: object
      properties:
        reader:
          $ref: '#/components/schemas/Reader'
      additionalProperties: true

