@startuml
start
repeat
    repeat
        if (Is packet type equal criterion packet type?) then (yes)

        endif
    repeat while (next criterion?) is (exist)
repeat while (next packet) is (exist)
end

@enduml