version: 1

root:
  handlers: [console]
  level:    DEBUG

disable_existing_loggers: true

loggers:
  InterfaceReader:
    level: DEBUG
  asyncio:
    level: ERROR
  pika:
    level: ERROR


handlers:
  console:
    class:     logging.StreamHandler
    formatter: json
    level:     DEBUG
    stream:    ext://sys.stdout

formatters:
  json:
    format:  "{'level': '%(levelname)s', 'time': '%(asctime)s', 'process': '%(process)s', 'thread': '%(threadName)s', 'function': '%(name)s.%(funcName)s:%(lineno)s', 'message': '%(message)s'}"
