# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class Reader(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PCAP = "pcap"
    INTERFACE = "interface"
    def __init__(self):  # noqa: E501
        """Reader - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Reader':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reader of this Reader.  # noqa: E501
        :rtype: Reader
        """
        return util.deserialize_model(dikt, cls)
