version: 1

root:
  handlers: [console]
  level:    DEBUG

disable_existing_loggers: true

loggers:
  pika:
    level: INFO


handlers:
  console:
    class:     logging.StreamHandler
    formatter: default
    level:     DEBUG
    stream:    ext://sys.stdout

formatters:
  default:
    format:  "[%(levelname)-8s] %(asctime)s '%(name)s.%(funcName)s:%(lineno)s': %(message)s"
